# Add prayer, complete prayer, fulfill prayer, edit prayer, delete prayer
(
    TYPING_PRAYER_REQ,
    TYPING_PRAYER,
    NEXT_PRAYER,
    COMPLETE_PRAYER,
    FULFILL_PRAYER,
    ADD_FULFILL_PRAYER,
    SET_FULFILL_PRAYER,
    CHOOSE_DEL_PRAYER,
    TYPING_DEL_PRAYER_PRAYERREQ,
    TYPING_DEL_PRAYER_REQ,
    TYPING_DEL_PRAYER_INDEX,
    TYPING_DEL_ANSWERED,
    DISPLAY_PICKED_PRAYER,
) = range(13)
