flowchart TB
A(("/start")):::entryPoint -->|Hi Prayer Warrior! Welcome to the MVP bot! ...| B{ }

B --> B1(/addprayer)
B --> B2(/completeprayer)
B --> B3(/addfulfillprayer)

B --> C1(/showprayer)
B --> C2(/showcompletedprayer)
B --> C3(/showvictory)
B --> C1(/showalluntrackedprayer)
